[package]
name = "candle-notebook"
version = "0.1.0"
edition = "2021"

[dependencies]
candle-core = "0.7.2"
candle-nn = "0.7.2"
serde = { version = "1.0.210", features = ["derive"] }

[dev-dependencies]
anyhow = "1.0.90"
crossterm = "0.28.1"
ratatui = "0.28.1"
