[package]
name = "candle-notebook"
version = "0.1.0"
edition = "2021"

[dependencies]
accelerate-src = { version = "0.3.2", optional = true }
bindgen_cuda = { version = "0.1.5", optional = true }
candle-core = "0.7.2"
candle-nn = "0.7.2"
half = "2.4.1"
intel-mkl-src = { version = "0.8.1", optional = true }
serde = { version = "1.0.214", features = ["derive"] }

[dev-dependencies]
anyhow = "1.0.92"
crossterm = "0.28.1"
ratatui = "0.29.0"
color-eyre = "0.6.3"
clap = { version = "4.5.20", features = ["derive"] }


[features]
default = []
accelerate = ["dep:accelerate-src", "candle-core/accelerate", "candle-nn/accelerate"]
cuda = ["candle-core/cuda", "candle-nn/cuda", "dep:bindgen_cuda"]
mkl = ["dep:intel-mkl-src", "candle-core/mkl", "candle-nn/mkl"]
metal = ["candle-core/metal", "candle-nn/metal"]
